---
author:
  email: 
  name: An Author
  twitter: 
  url: 
baseurl: "/alicia-newcome-a-story-workshop"
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.ecds.emory.edu/books/emory:191dd/pages/emory:gmgns/single-page/
image_size:
  page:
    width: 689
    height: 1000
  thumbnail:
    width: 206
    height: 300
  small-thumbnail:
    width: 68
    height: 100
permalink: pretty
publication_info:
  title: Alicia Newcome  a story of the upper Missouri., an annotated digital edition
  date: '2018'
  author: Victor, Frances Fuller, 1826-1902.
  editors: []
  tei_xml: tei.xml
show_annotation_author: true
source_info:
  title: Alicia Newcome  a story of the upper Missouri.
  author: Victor, Frances Fuller, 1826-1902.
  date: 1862?
  url: https://readux.ecds.emory.edu/books/emory:191dd/
  pdf_url: https://readux.ecds.emory.edu/books/emory:191dd/pdf/#page=2
  via_readux: true
tagline: ", an annotated digital edition"
title: Alicia Newcome  a story of the upper Missouri.
url: https://jcmundy.github.io
version: 0.7
